// Shared data for all direction renderers
window.LAB_DATA = {
  pi: {
    name: "Kok Hao Chen",
    credentials: "Ph.D.",
    role: "Principal Scientist II",
    affiliation: "Genome Institute of Singapore",
    photo: "pi.jpg",
    bio: "Pioneered MERFISH (Multiplexed Error-Robust FISH) during postdoctoral work at Harvard, enabling spatially resolved, highly multiplexed RNA profiling in single cells. The lab continues to develop new in situ omics technologies at GIS.",
    orcid: "https://orcid.org/0000-0001-7406-7919",
    scholar: "https://scholar.google.com/citations?user=H28iJakAAAAJ&hl=en",
    email: ["chenkh", "a-star.edu.sg"],
  },

  members: [
    { name: "Shijie Nigel Chou",    credentials: "Ph.D.", role: "Senior Scientist I",          photo: "person-nigel.jpg",   initial: "NC" },
    { name: "Xinrui Zhou",          credentials: "Ph.D.", role: "Senior Scientist I",          photo: "person-xinrui.png",  initial: "XZ" },
    { name: "Yen Ling Lee",         credentials: "",      role: "Lead Research Officer II",    photo: "person-yenling.jpg", initial: "YL" },
    { name: "Jiao Cao",             credentials: "Ph.D.", role: "Scientist",                   photo: "person-caojiao.jpg", initial: "JC" },
    { name: "Kaiyu Jin",            credentials: "Ph.D.", role: "Joint Research Fellow (NUS)",  photo: "", initial: "KJ" },
    { name: "Jose Guijarro Nuez",   credentials: "",      role: "A*STAR ARAP-MRC DTP PhD Student", photo: "person-jose.jpg",initial: "JG" },
    { name: "Matthew Kwok",         credentials: "",      role: "A*STAR–University of Warwick ARAP Joint PhD Student", photo: "", initial: "MK" },
  ],

  alumni: [
    { name: "Wan Yi Seow",          years: "2018–2025", current: "Senior Research Officer, Genome Institute of Singapore" },
    { name: "Dao Duc Tu",           years: "2023–2025", current: "Lecturer, Posts and Telecommunications Institute of Technology" },
    { name: "Maurice Lee Youzong",  years: "2020–2025", current: "Senior Scientist, Illumina" },
    { name: "Vipul Singhal",        years: "2018–2024", current: "Head of Computational Biology, Integrated Biosciences" },
    { name: "Lurong Wang",          years: "2022–2024", current: "Research Officer, Genome Institute of Singapore" },
    { name: "Jiamin Toh",           years: "2019–2024", current: "Research Officer, Genome Institute of Singapore" },
    { name: "Norbert Ha",           years: "2019–2024", current: "Biomedical Scientist, Delta Electronics" },
    { name: "Jack Petts-Lewis",     years: "2021–2023", current: "Graduate Student, University of Warwick" },
    { name: "Lingfan Jiang",        years: "2019–2023", current: "Research Scientist, KLA" },
    { name: "Jazlynn Tan",          years: "2022",      current: "University of Toronto" },
    { name: "Jeeranan Boonruangkan",years: "2018–2022", current: "Biofourmis" },
    { name: "Jolene Goh",           years: "2016–2022", current: "Veranome Biosystems" },
    { name: "Mike Jin-An Huang",    years: "2018–2021", current: "1910 Genetics" },
    { name: "Paul Cheng",           years: "2018–2021", current: "Veranome Biosystems" },
    { name: "Kaviya Selva Raju",    years: "2018–2020", current: "Research Associate, Applied Materials" },
    { name: "Siyi Chen",            years: "2018",      current: "Senior Scientist, Maiden Therapeutics" },
    { name: "Christabelle Goh",     years: "2018",      current: "Scientist II, Applied Materials" },
    { name: "Ziqing Winston Zhao",  years: "2018–2019", current: "Assistant Professor, National University of Singapore" },
    { name: "Teck Por Lim",         years: "2018–2019", current: "" },
    { name: "Mei Lun Chow",         years: "2018",      current: "Project Officer, Nanyang Technological University" },
  ],

  publications: [
    {
      year: 2026, journal: "Nature Communications", key: true,
      title: "Spatial perturb-seq: single-cell functional genomics within intact tissue architecture",
      authors: "Shen K., Seow W. Y., Keng C. T., Lim M. G. L., Lim D. S., Guo K., Meliani A., Hajis M. I. B., Wang B., Prabhakar S., Chen K. H., Chew W. L.",
      doi: "https://doi.org/10.1038/s41467-026-69677-6",
      tag: "Spatial perturb-seq",
    },
    {
      year: 2024, journal: "Nature Communications", key: true, thumb: "pub-fishnchips.png",
      title: "Highly sensitive spatial transcriptomics using FISHnCHIPs of multiple co-expressed genes",
      authors: "Zhou X.*, Seow W. Y.*, Ha N., Cheng T. H., Jiang L. F., Boonruangkan J., Goh J. J. L., Prabhakar S., Chou N.#, Chen K. H.#",
      doi: "https://www.nature.com/articles/s41467-024-46669-y",
      tag: "FISHnCHIPs",
    },
    {
      year: 2024, journal: "Nature Genetics", key: true, thumb: "pub-banksy.png",
      title: "BANKSY unifies cell typing and tissue domain segmentation for scalable spatial omics data analysis",
      authors: "Singhal V.*, Chou N.*, Lee J., Yue Y., Liu J., Chock W. K., Lin Li, Chang Y., Teo E., Lee H. K., Chen K. H.#, Prabhakar S.#",
      doi: "https://www.nature.com/articles/s41588-024-01664-3",
      tag: "BANKSY",
    },
    {
      year: 2020, journal: "Nature Methods", key: true, thumb: "pub-splitfish.png",
      title: "Highly specific multiplexed RNA imaging in tissues with split-FISH",
      authors: "Goh J. J. L.*, Chou N.*, Seow W. Y., Ha N., Cheng C. P. P., Chang Y., Zhao Z. W., Chen K. H.",
      doi: "https://www.nature.com/articles/s41592-020-0858-0",
      tag: "split-FISH",
    },
    {
      year: 2017, journal: "Nature Genetics",
      title: "Reference component analysis of single-cell transcriptomes elucidates cellular heterogeneity in human colorectal tumors",
      authors: "Li H., Courtois E. T., Sengupta D., Tan Y., Chen K. H., Goh J. J. L., et al.",
      doi: "https://www.nature.com/articles/ng.3818",
    },
    {
      year: 2016, journal: "PNAS",
      title: "High-throughput single-cell gene-expression profiling with multiplexed error-robust fluorescence in situ hybridization",
      authors: "Moffitt J. R.*, Hao J.*, Wang G.*, Chen K. H., Babcock H. P. & Zhuang X.",
      doi: "https://www.pnas.org/doi/10.1073/pnas.1612826113",
    },
    {
      year: 2015, journal: "Science", key: true, thumb: "pub-merfish.png",
      title: "Spatially resolved, highly multiplexed RNA profiling in single cells",
      authors: "Chen K. H.*, Boettiger A. N.*, Moffitt J. R.*, Wang S. & Zhuang X.",
      doi: "https://www.science.org/doi/10.1126/science.aaa6090",
      tag: "MERFISH",
    },
    { year: 2012, journal: "ACS Nano",
      title: "Understanding oligonucleotide-templated nanocrystals: Growth mechanisms and surface properties",
      authors: "Cha T. G., Baker B. A., Salgado J., Bates C. J., Chen K. H., Chang A. C., Han J. C., Strano M. S. & Choi J. H.",
      doi: "https://pubs.acs.org/doi/10.1021/nn302779m" },
    { year: 2012, journal: "ChemPhysChem",
      title: "Multicolor super-resolution fluorescence imaging via multi-parameter fluorophore detection",
      authors: "Bates M., Dempsey G. T., Chen K. H. & Zhuang X.",
      doi: "https://chemistry-europe.onlinelibrary.wiley.com/doi/10.1002/cphc.201100735" },
    { year: 2011, journal: "Lab on a Chip",
      title: "Wide-field single metal nanoparticle spectroscopy for high throughput localized surface plasmon resonance sensing",
      authors: "Chen K. H., Hobley J., Foo Y. L. & Su X.",
      doi: "https://pubs.rsc.org/en/content/articlelanding/2011/lc/c0lc00644k" },
    { year: 2011, journal: "Nature Methods",
      title: "Evaluation of fluorophores for optimal performance in localization-based super-resolution imaging",
      authors: "Dempsey G. T.*, Vaughan J. C.*, Chen K. H.*, Bates M. & Zhuang X.",
      doi: "https://www.nature.com/articles/nmeth.1768" },
    { year: 2010, journal: "Analytical Chemistry",
      title: "Temperature-independent porous nanocontainers for single-molecule fluorescence studies",
      authors: "Ishitsuka Y., Okumus B., Arslan S., Chen K. H. & Ha T.",
      doi: "https://pubs.acs.org/doi/10.1021/ac101714u" },
    { year: 2007, journal: "J. Phys. Chem. A",
      title: "Dispersion of single-walled carbon nanotubes with an extended diazapentacene derivative",
      authors: "Mateo-Alonso A., Ehli C., Chen K. H., Guldi D. M. & Prato M.",
      doi: "https://pubs.acs.org/doi/10.1021/jp0765648" },
    { year: 2006, journal: "JACS",
      title: "Aptamer-capped nanocrystal quantum dots: a new method for label-free protein detection",
      authors: "Choi J. H., Chen K. H. & Strano M. S.",
      doi: "https://pubs.acs.org/doi/10.1021/ja066506k" },
  ],

  research: [
    { tag: "MERFISH",      title: "In situ transcriptomics",
      desc: "We develop FISH-based methods — MERFISH, split-FISH, FISHnCHIPs — that image hundreds to thousands of RNA species simultaneously inside intact tissue, without dissociation." },
    { tag: "Spatial omics", title: "Spatial omics technology",
      desc: "Our platforms capture gene expression, cell identity, and tissue architecture in the same measurement, producing a molecular cartography of living systems." },
    { tag: "BANKSY",        title: "Computational analysis",
      desc: "We build open-source tools — including BANKSY — to extract biological insight from complex, high-dimensional spatial datasets at scale." },
    { tag: "Biology",       title: "Systems biology",
      desc: "We integrate spatial measurements with systems-level modeling to understand how gene regulatory networks operate in tissue context, and how they break in disease." },
  ],

  news: [
    { date: "Jan 2026", title: "Welcoming Matthew to the lab",
      note: "Matthew Kwok joins us as an A*STAR–University of Warwick ARAP Joint PhD student." },
    { date: "Mar 2024", title: "FISHnCHIPs published in Nature Communications",
      note: "A new method for highly sensitive spatial transcriptomics using co-expressed gene sets." },
    { date: "Apr 2024", title: "Welcoming Cao Jiao to the lab",
      note: "Cao Jiao joins us as a Scientist." },
    { date: "Feb 2024", title: "BANKSY out in Nature Genetics",
      note: "A unified framework for cell typing and tissue domain segmentation." },
    { date: "Sep 2024", title: "Welcoming Jose to the lab",
      note: "Jose joins us as an A*STAR ARAP-MRC DTP PhD scholar." },
    { date: "Ongoing",  title: "Positions available",
      note: "We are hiring post-doctoral fellows and research officers. Get in touch." },
  ],

  software: [
    { name: "split-fish", desc: "Multiplexed FISH image analysis pipeline used to analyze split-FISH data.",
      lang: "Python", paper: "Nature Methods, 2020",
      repo: "https://github.com/KHChenLab/split-fish",
      paperUrl: "https://www.nature.com/articles/s41592-020-0858-0" },
    { name: "FISHnCHIPs", desc: "Software for FISHnCHIPs — highly sensitive spatial transcriptomics using co-expressed gene sets.",
      lang: "Jupyter Notebook", paper: "Nature Communications, 2024",
      repo: "https://github.com/KHChenLab/FISHnCHIPs",
      paperUrl: "https://www.nature.com/articles/s41467-024-46669-y" },
    { name: "BANKSY", desc: "Unified framework for cell typing and tissue domain segmentation in spatial omics.",
      lang: "R / Python", paper: "Nature Genetics, 2024",
      repo: "https://github.com/prabhakarlab/Banksy",
      paperUrl: "https://www.nature.com/articles/s41588-024-01664-3" },
  ],

  gallery: [
    { src: "gallery-2026-02.jpg", date: "Feb 2026", caption: "Lo hei lunch" },
    { src: "gallery-2025-12.jpg", date: "Dec 2025", caption: "Christmas potluck" },
    { src: "gallery-2024-09.png", date: "Sep 2024", caption: "Lab outing" },
    { src: "gallery-2024-08.png", date: "Aug 2024", caption: "Group photo" },
    { src: "gallery-2023-07.png", date: "Jul 2023", caption: "Lab gathering" },
    { src: "gallery-2023-04.jpg", date: "Apr 2023", caption: "Windsor Nature Park" },
    { src: "gallery-2023-02.jpg", date: "Feb 2023", caption: "Hot pot night" },
    { src: "gallery-2022-11.png", date: "Nov 2022", caption: "Lab outing" },
    { src: "gallery-2022-04.jpg", date: "Apr 2022", caption: "Rail corridor walk" },
    { src: "gallery-2019-12.jpg", date: "Dec 2019", caption: "Year-end dinner" },
    { src: "gallery-2018-11.png", date: "Nov 2018", caption: "Halloween" },
    { src: "gallery-2018-10.jpg", date: "Oct 2018", caption: "Pizza lunch" },
  ],
};
